### ISSUE TITLE
ContentMapping.xml somehow broke

### ISSUE THREAD

**Issue by Wolfipoo** [Mowjoh/Quasar#11]
Don't quite know when and how it happened, but I'm pretty sure something broke along the way because the ContentMapping file has somehow became 791MB. And it's filled with a ridiculous amount of what I assume to be repeating text.

[ContentMapping.zip](https://github.com/Mowjoh/Quasar/files/6192364/ContentMapping.zip)

Don't know if this'll help, but this is what's in the Quasar log file. 
`2021-03-11 01:31:39,648 INFO - ------------------------------
2021-03-11 01:31:39,656 WARN - Quasar Start
2021-03-11 01:31:39,656 INFO - ------------------------------
2021-03-11 01:31:39,656 INFO - Update Process Started
2021-03-11 01:31:39,657 INFO - Started as a server
2021-03-11 01:31:39,693 INFO - Update Process Started
2021-03-11 01:31:40,231 INFO - Loading References
2021-03-11 01:31:58,722 INFO - Loading Views
2021-03-23 15:31:08,072 INFO - ------------------------------
2021-03-23 15:31:08,077 WARN - Quasar Start
2021-03-23 15:31:08,077 INFO - ------------------------------
2021-03-23 15:31:08,077 INFO - Update Process Started
2021-03-23 15:31:08,078 INFO - Started as a server
2021-03-23 15:31:08,098 INFO - Update Process Started
2021-03-23 15:31:08,330 INFO - Loading References
2021-03-23 15:31:48,744 INFO - There is an error in XML document (22683485, 37).
2021-03-23 15:31:48,767 INFO -    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Quasar.XMLResources.ContentXML.GetContentMappings()
   at Quasar.MainUIViewModel.GetContentMappings()
   at Quasar.MainUIViewModel.LoadStuff()
   at Quasar.MainUIViewModel..ctor()
2021-03-23 15:33:48,751 INFO - ------------------------------
2021-03-23 15:33:48,755 WARN - Quasar Start
2021-03-23 15:33:48,756 INFO - ------------------------------
2021-03-23 15:33:48,756 INFO - Update Process Started
2021-03-23 15:33:48,756 INFO - Started as a server
2021-03-23 15:33:48,760 INFO - Update Process Started
2021-03-23 15:33:48,854 INFO - Loading References
2021-03-23 15:33:59,574 INFO - There is an error in XML document (22683485, 37).
2021-03-23 15:33:59,578 INFO -    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Quasar.XMLResources.ContentXML.GetContentMappings()
   at Quasar.MainUIViewModel.GetContentMappings()
   at Quasar.MainUIViewModel.LoadStuff()
   at Quasar.MainUIViewModel..ctor()
2021-03-23 15:35:25,220 INFO - ------------------------------
2021-03-23 15:35:25,224 WARN - Quasar Start
2021-03-23 15:35:25,224 INFO - ------------------------------
2021-03-23 15:35:25,224 INFO - Update Process Started
2021-03-23 15:35:25,225 INFO - Started as a server
2021-03-23 15:35:25,229 INFO - Update Process Started
2021-03-23 15:35:25,308 INFO - Loading References
2021-03-23 15:35:36,075 INFO - There is an error in XML document (22683485, 37).
2021-03-23 15:35:36,079 INFO -    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Quasar.XMLResources.ContentXML.GetContentMappings()
   at Quasar.MainUIViewModel.GetContentMappings()
   at Quasar.MainUIViewModel.LoadStuff()
   at Quasar.MainUIViewModel..ctor()
2021-03-23 15:42:16,604 INFO - ------------------------------
2021-03-23 15:42:16,608 WARN - Quasar Start
2021-03-23 15:42:16,608 INFO - ------------------------------
2021-03-23 15:42:16,608 INFO - Update Process Started
2021-03-23 15:42:16,609 INFO - Started as a server
2021-03-23 15:42:16,613 INFO - Update Process Started
2021-03-23 15:42:16,701 INFO - Loading References
2021-03-23 15:42:27,579 INFO - There is an error in XML document (22683485, 37).
2021-03-23 15:42:27,582 INFO -    at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Quasar.XMLResources.ContentXML.GetContentMappings()
   at Quasar.MainUIViewModel.GetContentMappings()
   at Quasar.MainUIViewModel.LoadStuff()
   at Quasar.MainUIViewModel..ctor()
`

**Comment by Mowjoh** [comment]
I'm sorry this has happened. This is due to data models not being good and then those break. Unfortunately I cannot provide a solution since it can be broken in many ways.

The upcoming 2.0 release addresses this issue heavily
