### ISSUE TITLE
Quasar Frozen - Restarting/Re-Installing Does Not Work

### ISSUE THREAD

**Issue by Level100Mudkip** [Mowjoh/Quasar#21]
Quasar 2.1.0.1 has frozen. I've tried restarting my machine, uninstalling and repairing, none of which have fixed the issue.   
![image](https://user-images.githubusercontent.com/92429012/137093837-a4532770-6f7b-48e0-94d0-92c194bd150c.png)

**Comment by WinnieDaAuchwitz** [comment]
I fixed it by deleting Library.json

**Comment by mugwhump** [comment]
Yeah it doesn't play nicely with attempts to change the Quasar directory. Uninstalling and reinstalling didn't help, could find where is stored the Quasar directory path in either the installation folder or the registry. Had to put the stuff back where it was on initial install.

Currently it shows the basic UI for me, but when I launch it or try to download something I'm getting the error: 
`Could not find file 'B:\Quasar\Library\Library.json'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Quasar.Helpers.FileOperations.FileOperation.CheckCopyFile(String source, String destination)
   at Quasar.Helpers.Quasar_Management.InstallManager.BackupUserData()
   at Quasar.MainUI.ViewModels.MainUIViewModel.BackupRestoreUserData(Boolean LoadSuccess)
   at Quasar.MainUI.ViewModels.MainUIViewModel..ctor()
`
