### ISSUE TITLE
Error screen on launch

### ISSUE THREAD

**Issue by jakecybr** [Mowjoh/Quasar#29]
While installing mods my disk drive ran out of space, I have since remedied the issue.
I have
reinstalled Quasar
![quasar error](https://user-images.githubusercontent.com/103164130/162117931-3d6f9aff-917a-4bbd-a995-99d2340f7b4b.PNG)

deleted all associated files and tried again
tried the repair option
cleared my mods folder

The error throws no codes that I know of, and has no text, no message, us two blank message prompts.
If I am leaving an issue here incorrectly please let me know, I just created my account to leave a message here.

**Comment by jakecybr** [comment]
I am sorry for the above issue post with not a lot of information

I am on the latest version
I have more than enough storage space currently
I did not move any installation folders around, ,I saw a similar error being cause by such action.

the log file says the below:

> at Workshop.FileManagement.ResourceManager.CleanGamebananaAPIFile(GamebananaAPI API, ObservableCollection`1 Library)
   at Quasar.MainUI.ViewModels.MainUIViewModel.LoadData() in M:\Repos\Quasar\Quasar\Application\MainUI\ViewModels\MainUIViewModel.cs:line 482
   at Quasar.MainUI.ViewModels.MainUIViewModel..ctor() in M:\Repos\Quasar\Quasar\Application\MainUI\ViewModels\MainUIViewModel.cs:line 388

Again, I have never used this website for more than downloading, so if I have left this in the wrong area / incorrectly I do apologize and can remove this post

**Comment by jakecybr** [comment]
I am sorry for the above issue post with not a lot of information

I am on the latest version
I have more than enough storage space currently
I did not move any installation folders around, ,I saw a similar error being cause by such action.
the log file says the below:

>2022-04-07 03:10:04,440 INFO - ------------------------------
2022-04-07 03:10:04,444 WARN - Quasar Start
2022-04-07 03:10:04,444 INFO - ------------------------------
2022-04-07 03:10:04,444 INFO - Tunnel Setup
2022-04-07 03:10:04,445 INFO - Started as a server
2022-04-07 03:10:04,446 INFO - Update Process Started
2022-04-07 03:10:04,447 DEBUG - No Update
2022-04-07 03:10:04,449 DEBUG - Loading Data
2022-04-07 03:10:04,688 ERROR - Object reference not set to an instance of an object.
2022-04-07 03:10:04,708 ERROR -    at Workshop.FileManagement.ResourceManager.CleanGamebananaAPIFile(GamebananaAPI API, ObservableCollection`1 Library)
   at Quasar.MainUI.ViewModels.MainUIViewModel.LoadData() in M:\Repos\Quasar\Quasar\Application\MainUI\ViewModels\MainUIViewModel.cs:line 482
   at Quasar.MainUI.ViewModels.MainUIViewModel..ctor() in M:\Repos\Quasar\Quasar\Application\MainUI\ViewModels\MainUIViewModel.cs:line 388


Again, I have never used this website for more than downloading, so if I have left this in the wrong area / incorrectly I do apologize and can remove this post
[Quasar.log](https://github.com/Mowjoh/Quasar/files/8440991/Quasar.log)

**Comment by joeastrong** [comment]
I recently got this same screen when my power went out abruptly on my PC while it was running...any advice? Tried repairing the installation with no luck. Any tips?

![Screenshot 2022-05-06 210831](https://user-images.githubusercontent.com/98445078/167231969-8438d8bf-76aa-4a50-a916-307eb6e145f6.png)
