### ISSUE TITLE
Can't launch Quasar

### ISSUE THREAD

**Issue by tjcr** [Mowjoh/Quasar#9]
Hi, I'm getting this error: 

2021-03-12 01:23:15,155 INFO - ------------------------------
2021-03-12 01:23:15,161 WARN - Quasar Start
2021-03-12 01:23:15,161 INFO - ------------------------------
2021-03-12 01:23:15,161 INFO - Update Process Started
2021-03-12 01:23:15,161 INFO - Started as a server
2021-03-12 01:23:15,167 INFO - Update Process Started
2021-03-12 01:23:15,437 INFO - Access to the path 'Delete.png' is denied.
2021-03-12 01:23:15,442 INFO -    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Quasar.FileSystem.Folderino.CheckClearFolder(String SourceFolderPath)
   at Quasar.FileSystem.Folderino.CopyFolder(String SourceFolderPath, String DestinationFolderPath, Boolean ClearDestination)
   at Quasar.FileSystem.Folderino.UpdateBaseFiles()
   at Quasar.Internal.Tools.Updater..ctor()
   at Quasar.MainUIViewModel..ctor()

Any idea how to fix it?
I feel like the path of Delete.png should be ":\Users\<name>\Documents\Quasar\References\images\Delete.png" maybe?

**Comment by tjcr** [comment]
OK for some reason it started working, though I didn't do anything. It might have been a firewall thing even though I tried it with firewalls disabled before.
